// <auto-generated />
using System;
using CommonShop.SalesService.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace CommonShop.SalesService.Migrations
{
    [DbContext(typeof(SalesDbContext))]
    partial class SalesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("CommonShop.SalesService.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("StockLevel")
                        .HasColumnType("integer");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("de039434-d200-43b9-8191-79869c895821"),
                            Category = "Category 1",
                            Description = "Some description",
                            Price = 10m,
                            Quantity = 2,
                            StockLevel = 0,
                            ThumbnailUrl = "https://bulma.io/images/placeholders/640x480.png",
                            Title = "Product 1"
                        },
                        new
                        {
                            Id = new Guid("d6a76809-7088-465d-bfe8-4d95c4f38c40"),
                            Category = "Category 2",
                            Description = "Some description",
                            Price = 20m,
                            Quantity = 3,
                            StockLevel = 0,
                            ThumbnailUrl = "https://bulma.io/images/placeholders/640x480.png",
                            Title = "Product 2"
                        },
                        new
                        {
                            Id = new Guid("387ba502-67ff-4cc5-ab50-15d436a4b455"),
                            Category = "Category 1",
                            Description = "Some description",
                            Price = 30m,
                            Quantity = 1,
                            StockLevel = 0,
                            ThumbnailUrl = "https://bulma.io/images/placeholders/640x480.png",
                            Title = "Product 3"
                        },
                        new
                        {
                            Id = new Guid("a14ac91b-1ad1-40c4-8092-d08109e5ca78"),
                            Category = "Category 2",
                            Description = "Some description",
                            Price = 40m,
                            Quantity = 2,
                            StockLevel = 0,
                            ThumbnailUrl = "https://bulma.io/images/placeholders/640x480.png",
                            Title = "Product 4"
                        },
                        new
                        {
                            Id = new Guid("c0cd14c3-c55c-4b94-a4bd-7298e7eff811"),
                            Category = "Category 1",
                            Description = "Some description",
                            Price = 50m,
                            Quantity = 3,
                            StockLevel = 0,
                            ThumbnailUrl = "https://bulma.io/images/placeholders/640x480.png",
                            Title = "Product 5"
                        },
                        new
                        {
                            Id = new Guid("e10fcad7-a24f-416f-a43e-0fc1fce71727"),
                            Category = "Category 2",
                            Description = "Some description",
                            Price = 60m,
                            Quantity = 1,
                            StockLevel = 0,
                            ThumbnailUrl = "https://bulma.io/images/placeholders/640x480.png",
                            Title = "Product 6"
                        },
                        new
                        {
                            Id = new Guid("3c72192c-578f-4e37-9061-029f70f94b8b"),
                            Category = "Category 1",
                            Description = "Some description",
                            Price = 70m,
                            Quantity = 2,
                            StockLevel = 0,
                            ThumbnailUrl = "https://bulma.io/images/placeholders/640x480.png",
                            Title = "Product 7"
                        },
                        new
                        {
                            Id = new Guid("5114e1c1-0ad1-44bc-88cb-cbe70ee07c3e"),
                            Category = "Category 2",
                            Description = "Some description",
                            Price = 80m,
                            Quantity = 3,
                            StockLevel = 0,
                            ThumbnailUrl = "https://bulma.io/images/placeholders/640x480.png",
                            Title = "Product 8"
                        },
                        new
                        {
                            Id = new Guid("b6890fea-68a6-4188-aec2-9e99c71f0c9a"),
                            Category = "Category 1",
                            Description = "Some description",
                            Price = 90m,
                            Quantity = 1,
                            StockLevel = 0,
                            ThumbnailUrl = "https://bulma.io/images/placeholders/640x480.png",
                            Title = "Product 9"
                        },
                        new
                        {
                            Id = new Guid("48347309-5131-4cbc-aed7-9a64b40059c4"),
                            Category = "Category 2",
                            Description = "Some description",
                            Price = 100m,
                            Quantity = 2,
                            StockLevel = 0,
                            ThumbnailUrl = "https://bulma.io/images/placeholders/640x480.png",
                            Title = "Product 10"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
